#!/usr/bin/env python3

from collections import defaultdict, deque
from pathlib import Path
import sys


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(rows)


def compress(data: bytes) -> bytes:
    """Encode bytes as flag groups of literals and 12-bit-window matches."""
    positions: dict[bytes, deque[int]] = defaultdict(deque)
    output = bytearray()
    offset = 0

    def remember(start: int, length: int) -> None:
        for index in range(start, min(start + length, len(data) - 2)):
            key = data[index : index + 3]
            candidates = positions[key]
            candidates.append(index)
            while candidates and index - candidates[0] > 4096:
                candidates.popleft()

    while offset < len(data):
        flag_offset = len(output)
        output.append(0)
        flags = 0
        for bit in range(8):
            if offset >= len(data):
                break

            best_length = 0
            best_distance = 0
            if offset + 3 <= len(data):
                candidates = positions[data[offset : offset + 3]]
                while candidates and offset - candidates[0] > 4096:
                    candidates.popleft()
                for candidate in reversed(candidates):
                    distance = offset - candidate
                    length = 3
                    limit = min(18, len(data) - offset)
                    while (
                        length < limit
                        and data[candidate + length] == data[offset + length]
                    ):
                        length += 1
                    if length > best_length:
                        best_length = length
                        best_distance = distance
                        if length == 18:
                            break

            if best_length >= 3:
                encoded_distance = best_distance - 1
                output.append(encoded_distance & 0xFF)
                output.append(((encoded_distance >> 8) << 4) | (best_length - 3))
                remember(offset, best_length)
                offset += best_length
            else:
                flags |= 1 << bit
                output.append(data[offset])
                remember(offset, 1)
                offset += 1
        output[flag_offset] = flags
    return bytes(output)


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print(f"usage: {sys.argv[0]} INPUT.zsh OUTPUT.c [FUNCTION]", file=sys.stderr)
        return 2

    source = Path(sys.argv[1])
    output = Path(sys.argv[2])
    function = sys.argv[3] if len(sys.argv) == 4 else "nbsp_print_zsh_init"
    array_name = function.removeprefix("nbsp_print_")
    data = source.read_bytes()
    packed = compress(data)

    generated = f"""\
/* Generated by tools/embed_zsh.py. Do not edit. */
#include "nbsp_zsh.h"

static const unsigned char {array_name}_packed[] = {{
{format_bytes(packed)}
}};

void {function}(FILE *out) {{
    unsigned char decoded[{len(data)}];
    size_t input_offset = 0U;
    size_t output_offset = 0U;
    while (input_offset < sizeof({array_name}_packed) &&
        output_offset < sizeof(decoded)) {{
        unsigned int flags = {array_name}_packed[input_offset++];
        for (unsigned int bit = 0U;
            bit < 8U && output_offset < sizeof(decoded);
            ++bit) {{
            if ((flags & (1U << bit)) != 0U) {{
                if (input_offset >= sizeof({array_name}_packed)) return;
                decoded[output_offset++] = {array_name}_packed[input_offset++];
                continue;
            }}
            if (input_offset + 1U >= sizeof({array_name}_packed)) return;
            unsigned int low = {array_name}_packed[input_offset++];
            unsigned int high_and_length = {array_name}_packed[input_offset++];
            size_t distance =
                (size_t)(low | ((high_and_length >> 4U) << 8U)) + 1U;
            size_t length = (size_t)(high_and_length & 0x0fU) + 3U;
            if (distance > output_offset ||
                length > sizeof(decoded) - output_offset) return;
            for (size_t index = 0U; index < length; ++index) {{
                decoded[output_offset] = decoded[output_offset - distance];
                ++output_offset;
            }}
        }}
    }}
    if (input_offset == sizeof({array_name}_packed) &&
        output_offset == sizeof(decoded)) {{
        (void)fwrite(decoded, 1U, sizeof(decoded), out);
    }}
}}
"""
    output.write_bytes(generated.encode("ascii"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
