#!/usr/bin/env python3

from pathlib import Path
import sys


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(rows)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} INPUT.zsh OUTPUT.c", file=sys.stderr)
        return 2

    source = Path(sys.argv[1])
    output = Path(sys.argv[2])
    data = source.read_bytes()

    generated = f"""\
/* Generated by tools/embed_zsh.py. Do not edit. */
#include "nbsp_zsh.h"

static const unsigned char nbsp_zsh_init[] = {{
{format_bytes(data)}
}};

void nbsp_print_zsh_init(FILE *out) {{
    (void)fwrite(nbsp_zsh_init, 1, sizeof(nbsp_zsh_init), out);
}}
"""
    output.write_bytes(generated.encode("ascii"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
