#include "nbsp_zsh.h"

void nbsp_print_zsh_init(FILE *out) {
    fputs(
        "if [[ -z ${_NBSP_INITIALIZED-} ]]; then\n"
        "  typeset -g _NBSP_INITIALIZED=1\n"
        "  autoload -Uz add-zsh-hook\n"
        "  zmodload zsh/datetime\n"
        "  zmodload zsh/parameter\n"
        "  zmodload zsh/system 2>/dev/null\n"
        "\n"
        "  typeset -gx NBSP_COLOR_PATH=${NBSP_COLOR_PATH:-default}\n"
        "  typeset -gx NBSP_COLOR_GIT=${NBSP_COLOR_GIT:-default}\n"
        "  typeset -gx NBSP_COLOR_NODE=${NBSP_COLOR_NODE:-green}\n"
        "  typeset -gx NBSP_COLOR_META=${NBSP_COLOR_META:-yellow}\n"
        "  typeset -gx NBSP_COLOR_OK=${NBSP_COLOR_OK:-none}\n"
        "  typeset -gx NBSP_COLOR_ERROR=${NBSP_COLOR_ERROR:-red}\n"
        "  typeset -gx NBSP_PROMPT_CHAR=${NBSP_PROMPT_CHAR:-%#}\n"
        "  typeset -gx NBSP_DURATION_THRESHOLD_MS=${NBSP_DURATION_THRESHOLD_MS:-2000}\n"
        "  typeset -gx NBSP_GIT_TIMEOUT_MS=${NBSP_GIT_TIMEOUT_MS:-1500}\n"
        "  typeset -gx NBSP_SHOW_GIT=${NBSP_SHOW_GIT:-1}\n"
        "  typeset -gx NBSP_SHOW_NVM=${NBSP_SHOW_NVM:-1}\n"
        "  typeset -gx NBSP_SHOW_JOBS=${NBSP_SHOW_JOBS:-1}\n"
        "  [[ -n ${NBSP_CACHE_DIR-} ]] && export NBSP_CACHE_DIR\n"
        "\n"
        "  typeset -gF _nbsp_started_at=0\n"
        "  typeset -gi _nbsp_last_status=0\n"
        "  typeset -gi _nbsp_last_duration_ms=0\n"
        "  typeset -gi _nbsp_last_jobs=0\n"
        "  typeset -gi _nbsp_refresh_fd=-1\n"
        "  typeset -gi _nbsp_refresh_again=0\n"
        "  typeset -g _nbsp_refresh_pwd=\n"
        "  typeset -g _nbsp_prompt_body=\n"
        "\n"
        "  _nbsp_render() {\n"
        "    local rendered old pattern kept_prefix kept_suffix\n"
        "    rendered=$(command nbsp prompt \\\n"
        "      --status \"$_nbsp_last_status\" \\\n"
        "      --duration-ms \"$_nbsp_last_duration_ms\" \\\n"
        "      --jobs \"$_nbsp_last_jobs\")\n"
        "    if [[ $? != 0 || -z $rendered ]]; then\n"
        "      rendered='> '\n"
        "    fi\n"
        "    old=$_nbsp_prompt_body\n"
        "    if [[ -n $old ]]; then\n"
        "      pattern=${(b)old}\n"
        "    fi\n"
        "    if [[ -n $old && $PROMPT == *${~pattern}* ]]; then\n"
        "      kept_prefix=${PROMPT%%${~pattern}*}\n"
        "      kept_suffix=${PROMPT#*${~pattern}}\n"
        "      PROMPT=${kept_prefix}${rendered}${kept_suffix}\n"
        "    else\n"
        "      PROMPT=$rendered\n"
        "    fi\n"
        "    _nbsp_prompt_body=$rendered\n"
        "  }\n"
        "\n"
        "  _nbsp_cancel_refresh() {\n"
        "    if (( _nbsp_refresh_fd >= 0 )); then\n"
        "      zle -F \"$_nbsp_refresh_fd\" 2>/dev/null\n"
        "      { exec {_nbsp_refresh_fd}<&- } 2>/dev/null\n"
        "      _nbsp_refresh_fd=-1\n"
        "    fi\n"
        "    _nbsp_refresh_again=0\n"
        "    _nbsp_refresh_pwd=\n"
        "  }\n"
        "\n"
        "  _nbsp_refresh_done() {\n"
        "    local fd=$1 ignored refresh_pwd=$_nbsp_refresh_pwd\n"
        "    local -i refresh_again=$_nbsp_refresh_again\n"
        "    read -r -u \"$fd\" ignored 2>/dev/null\n"
        "    zle -F \"$fd\" 2>/dev/null\n"
        "    { exec {fd}<&- } 2>/dev/null\n"
        "    (( fd == _nbsp_refresh_fd )) || return\n"
        "    _nbsp_refresh_fd=-1\n"
        "    _nbsp_refresh_again=0\n"
        "    if [[ $PWD == $refresh_pwd ]]; then\n"
        "      if (( refresh_again )); then\n"
        "        _nbsp_schedule_refresh 1\n"
        "      else\n"
        "        _nbsp_render\n"
        "        zle reset-prompt 2>/dev/null\n"
        "      fi\n"
        "    fi\n"
        "  }\n"
        "\n"
        "  _nbsp_schedule_refresh() {\n"
        "    local -i force=${1:-0}\n"
        "    local -i raw_fd=-1\n"
        "    local -a refresh_args=(refresh --cwd \"$PWD\" --notify)\n"
        "    [[ $NBSP_SHOW_GIT == 0 ]] && return\n"
        "    if (( _nbsp_refresh_fd >= 0 )); then\n"
        "      [[ $_nbsp_refresh_pwd == $PWD ]] && return\n"
        "      _nbsp_cancel_refresh\n"
        "    fi\n"
        "    (( force )) && refresh_args+=(--force)\n"
        "    _nbsp_refresh_pwd=$PWD\n"
        "    _nbsp_refresh_again=0\n"
        "    exec {raw_fd}< <(command nbsp \"${refresh_args[@]}\" 2>/dev/null)\n"
        "    if (( $+builtins[sysopen] )) && \\\n"
        "        sysopen -o cloexec -ru _nbsp_refresh_fd -- /dev/fd/$raw_fd 2>/dev/null; then\n"
        "      { exec {raw_fd}<&- } 2>/dev/null\n"
        "    else\n"
        "      _nbsp_refresh_fd=$raw_fd\n"
        "    fi\n"
        "    if ! zle -F \"$_nbsp_refresh_fd\" _nbsp_refresh_done 2>/dev/null; then\n"
        "      _nbsp_cancel_refresh\n"
        "    fi\n"
        "  }\n"
        "\n"
        "  _nbsp_preexec() {\n"
        "    (( _nbsp_refresh_fd >= 0 )) && _nbsp_refresh_again=1\n"
        "    _nbsp_started_at=$EPOCHREALTIME\n"
        "  }\n"
        "\n"
        "  _nbsp_precmd() {\n"
        "    _nbsp_last_status=$?\n"
        "    if (( _nbsp_started_at > 0 )); then\n"
        "      _nbsp_last_duration_ms=$(( (EPOCHREALTIME - _nbsp_started_at) * 1000.0 ))\n"
        "    else\n"
        "      _nbsp_last_duration_ms=0\n"
        "    fi\n"
        "    _nbsp_started_at=0\n"
        "    _nbsp_last_jobs=${#jobstates}\n"
        "    _nbsp_render\n"
        "    _nbsp_schedule_refresh\n"
        "  }\n"
        "\n"
        "  _nbsp_chpwd() {\n"
        "    _nbsp_cancel_refresh\n"
        "  }\n"
        "\n"
        "  add-zsh-hook preexec _nbsp_preexec\n"
        "  add-zsh-hook precmd _nbsp_precmd\n"
        "  add-zsh-hook chpwd _nbsp_chpwd\n"
        "fi\n",
        out);
}
